---
- name: Install Redis
  ansible.builtin.apt:
    name: redis-server
    state: present
    update_cache: true

- name: Start Redis
  ansible.builtin.systemd:
    name: redis-server
    enabled: true
    state: started

