---
- hosts: all
  become: true
  roles:
    - base

- hosts: redis
  become: true
  roles:
    - redis

- hosts: postgresql
  roles:
    - postgresql

- hosts: poll
  roles:
    - poll

- hosts: result
  roles:
    - result

- hosts: worker
  roles:
    - worker
