---
- hosts: all
  become: true
  roles:
    - base

- hosts: redis
  become: true
  roles:
    - redis

# - hosts: postgresql
#   become: true
#   roles:
#     - postgresql
#
# - hosts: poll
#   become: true
#   roles:
#     - poll
#
# - hosts: result
#   become: true
#   roles:
#     - result
#
# - hosts: worker
#   become: true
#   roles:
#     - worker
