# TYPE  DATABASE  USER      ADDRESS         METHOD
local   all       postgres                  peer
host    paul      paul      127.0.0.1/32    md5
host    paul      paul      0.0.0.0/0       md5
host    paul      paul      ::/0            md5
