bind 0.0.0.0
protected-mode no
port 6379
timeout 0
tcp-keepalive 300
daemonize no
supervised systemd
loglevel notice
logfile /var/log/redis/redis-server.log
databases 16
save ""
stop-writes-on-bgsave-error no
