---
- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600

- name: Install useful packages
  ansible.builtin.apt:
    name:
      - python3
      - python3-venv
      - python3-packaging
      - curl
      - vim
      - tar
      - ca-certificates
      - gnupg
      - apt-transport-https
      - lsb-release
      - net-tools
    state: present

- name: Set Timezone
  community.general.timezone:
    name: "{{timezone | default('Europe/Paris')}}"
